declare namespace NodeJS {
  export interface ProcessEnv {
    readonly NODE_ENV: string
    readonly NEST_APP_DATABASE_URL: string
    readonly NEST_APP_PROTOCOL: string
    readonly NEST_APP_HOST: string
    readonly NEST_APP_PORT: string
    readonly NEST_APP_JWT_SECRET: string
    readonly NEST_APP_JWT_EXPIRES: string
    readonly NEST_APP_JWT_REFRESH_SECRET: string
    readonly NEST_APP_JWT_REFRESH_EXPIRES: string
    readonly NEST_APP_JWT_STOREFRONT_SECRET: string
    readonly NEST_APP_JWT_STOREFRONT_EXPIRES: string
    readonly NEST_APP_EMAIL_HOST: string
    readonly NEST_APP_EMAIL_PORT: string
    readonly NEST_APP_EMAIL_HOST_USER: string
    readonly NEST_APP_EMAIL_HOST_PASSWORD: string
    readonly NEST_APP_EMAIL_FROM: string
    readonly NEST_APP_EMAIL_IGNORE_TLS: string
    readonly NEST_APP_I18N_DEFAULT: string
    readonly NEST_APP_EMAIL_SECURE: string
    readonly NEST_APP_EMAIL_PREVIEW: string
    readonly NEST_APP_SWAGGER_USER: string
    readonly NEST_APP_SWAGGER_PASSWORD: string
    readonly NEST_APP_AMAP_API_KEY: string
    readonly NEST_APP_CHUNZHEN_IP_API_CODE: string
    readonly NEST_APP_WEICHAT_OPEN_URL: string
    readonly NEST_APP_WEICHAT_API_URL: string
    readonly NEST_APP_WEICHAT_APP_ID: string
    readonly NEST_APP_WEICHAT_APP_SECRET: string
    readonly NEST_APP_WEICHAT_TOKEN: string
    readonly NEST_APP_WEICHAT_ENCODING_AESKEY: string
    readonly NEST_APP_WEICHAT_TEMPLATE_ID: string
    readonly NEST_APP_FRONT_URL: string
    readonly NEST_APP_BACKEND_URL: string
    readonly NEST_APP_ALIYUN_SMS_ACCESS_KEY_ID: string
    readonly NEST_APP_ALIYUN_SMS_ACCESS_KEY_SECRET: string
    readonly NEST_APP_ALIYUN_SMS_SIGN_NAME: string
    readonly NEST_APP_ALIYUN_OSS_ACCESS_KEY_ID: string
    readonly NEST_APP_ALIYUN_OSS_ACCESS_KEY_SECRET: string
    readonly NEST_APP_ALIYUN_OSS_BUCKET: string
    readonly NEST_APP_ALIYUN_OSS_REGION: string
    readonly NEST_APP_ALIYUN_OSS_RAM_ROLE_ARN: string
    readonly NEST_APP_REDIS_HOST: string
    readonly NEST_APP_REDIS_PORT: string
    readonly NEST_APP_REDIS_PASSWORD: string
    readonly NEST_APP_REDIS_DB: string
  }
}
